package asgn1Question;

/**
 * This class represents any exceptions generated by the warehouse
 * simulation.  If you find that the parameters provided to your
 * methods are invalid then you should throw a new instance of
 * this class.
 * 
 * @author INB370 
 * @version 1.0
 */
@SuppressWarnings("serial") // We're not interested in binary i/o here
public class WarehouseException extends Exception {
	
	/**
	 * Creates a new instance of WarehouseException.
	 * 
	 * @param message an informative message about the problem found
	 */
	public WarehouseException(String message) {
		super("Warehouse Exception: " + message);
	}
}
